=== bouissai/Tux/src/game/Data/xsd/hi-scores.xsd
<?xml version="1.0"?>
<!--
XML SCHEMA du document hi-scores.xml qui correspond aux 
10 meilleurs scores du jeu
-->

<xs:schema version="1.0"
           xmlns="http://myGame/tux"
           targetNamespace="http://myGame/tux"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="scores" type="Scores"/>
    <xs:complexType name="Scores">
        <xs:sequence>
            <xs:element name="score" type="xs:double" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== bouissai/Tux/src/game/Data/xml/hi-scores.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
    Document   : dico.xml
    Author     : BOUISSA Ilyass / CRIVOI Dmtrii
    Description: DonnÃ©es des 10 meilleures scores du jeu
-->
<scores xmlns="http://myGame/tux" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://myGame/tux ../xsd/hi-scores.xsd">
    <score>75</score>
    <score>60</score>
    <score>60</score>
    <score>50</score>
    <score>50</score>
    <score>44</score>
    <score>44</score>
    <score>40</score>
    <score>38</score>
    <score>37</score>
</scores>
